name: run scraper.py

on:
  schedule:
    - cron: "0 12 * * *" # At 12:00 GMT everyday

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10.5" # install the python version needed

      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: execute py script # run scraper.py
        env:
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
        run: python scraper.py
